spring:
  profiles:
    active: local

---

spring.config.activate.on-profile: local

spring:
  # datasource
  datasource:
    url: jdbc:h2:mem:database

  # sql init
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 1800000 # 30 minutes

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: trace
            StatementCreatorUtils: trace
          datasource:
            init: trace
